# Baconfreak Configuration
# Modern configuration using TOML format with plugin architecture
#
# This configuration supports:
# - Plugin-based architecture (BLE and WiFi plugins)
# - String-based interface names (e.g., "hci1", "wlan0")
# - No fallback interfaces (graceful error handling on interface failure)
# - Individual plugin enable/disable support
#
# Environment prefix: BFREAK_
# Example: BFREAK_LOGGING_LEVEL=DEBUG
#
# Plugin Control:
# - Set enabled=false in plugin config to disable
# - Use --enable-plugin <name> or --disable-plugin <name> CLI options to override

[paths]
base_dir = "."
output_dir = "output"
assets_dir = "assets"
external_dir = "external"
logs_dir = "logs"

[output]
# PCAP file naming (updated to match current defaults)
known_pcap = "bfreak-known.pcap"      # Known company devices
unknown_pcap = "bfreak-unknown.pcap"  # Unknown company devices  
devices_pcap = "bfreak-devices.pcap"  # Specific device types
device_types_for_devices_pcap = ["tile", "airtag_unregistered", "airtag_registered"]

[database]
company_identifiers_db = "company_identifiers.db"
oui_identifiers_db = "oui_identifiers.db"
batch_size = 500
sources = [
    "company_identifiers.yaml",
    "custom_identifiers.yaml"
]
oui_sources = [
    "oui_identifiers.yaml",
    "custom_oui_identifiers.yaml"
]

[detection]
device_timeout = 300  # seconds
min_rssi = -100      # dBm
max_devices = 10000  # maximum devices to track

[logging]
level = "INFO"
# file = "baconfreak.log"  # uncomment to enable file logging
rotation = "10 MB"
retention = "7 days"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

[rich]
# Rich console settings
console_width = 120
console_force_terminal = false
console_no_color = false

[performance]
packet_buffer_size = 1000
statistics_interval = 10  # seconds

[plugins]
# Modern plugin architecture - each plugin has its own configuration

[plugins.ble]
# BLE plugin configuration
enabled = true                      # Enable/disable BLE plugin
interface = "hci1"                  # HCI interface (e.g., hci0, hci1)
adapter_name = "Built-in Bluetooth" # Bluetooth adapter name for display
scan_timeout = 0                    # Scan timeout in seconds (0=infinite)
filter_duplicates = false           # Filter duplicate advertisements
min_rssi = -100                     # Minimum RSSI threshold (-127 to 20)

[plugins.wifi]
# WiFi packet capture plugin configuration  
enabled = false                # Enable/disable WiFi plugin
interface = "wlan1"           # WiFi interface name (override with --wifi-interface)
monitor_mode = true           # Enable monitor mode for packet capture
scan_timeout = 0              # Scan timeout in seconds (0=infinite)
channel_hop = true            # Enable channel hopping
channels = [1, 6, 11]         # Manual channel list (overrides band settings)
enable_2_4ghz = true          # Enable 2.4GHz band channels (1-14)
enable_5ghz = false           # Enable 5GHz band channels (36-165)
enable_6e = false             # Enable 6E band channels (1-233)
min_rssi = -100               # Minimum RSSI threshold (-127 to 20)
channel_hop_interval = 2.0   # Channel hop interval in seconds